Stats:
    potionEffect: false
    deathMessages: true

Nickname:
    allowFormat: false
    characterlimit: 15
  
Message:
    mentionTag: "@"
    mentionColour: "&b&n"
    receiveSound: "ENTITY_CHICKEN_EGG"
    mentionSound: "ENTITY_ENDER_DRAGON_GROWL"
  
# Wether or not to immediatly consume consumables (potions, food, etc)
immediateConsuming: true

WorldGuard:
    disableWandPvP: true
    
    # How much blocks from the players location relative to the border should be shown.
    # If visibleBorderLeeway is set to 2, the players will see 25 blocks in the border (5*5).
    # Default: 2 
    visibleBorderLeeway: 2

# Magic Wand settings
wand:
    enabled: true
    name: '&5Magic Wand'
    material: STICK
    
    # gives enchanted glow
    enchanted: true
    
    # cooldown in seconds for wand use. Set to 0 for no cooldown
    cooldown: 10
    
    secondaryCooldown: 5
    
    secondaryDamage: 0.25
    
    # the lore for the item
    lore:
    - 'Left Click: &3strike your foes with &6lightning from olympus itself&3!'
    - 'Right Click: &3punish those who oppose you!'

# Dragon stick settings
dragonstick:
    enabled: true
    name: '&6&lStick of the &4&lDragon'
    material: BLAZE_ROD
    
    # gives enchanted glow
    enchanted: true

    # cooldown in seconds for wand use. Set to 0 for no cooldown
    cooldown: 15
    
    secondaryCooldown: 5
    
    secondaryDamage: 0.4
    
    # the lore for the item
    lore:
    - 'Left Click: &3make thine enemies explode!'
    - 'Right Click: &3burn thine enemies ALIVE!'
  