Stats:
    potionEffect: false
    deathMessages: true
    scoreboard: true

Nickname:
    allowFormat: false
    characterlimit: 15
  
Message:
    mentionTag: "@"
    mentionColour: "&b&n"
    receiveSound: "ENTITY_CHICKEN_EGG"
    mentionSound: "ENTITY_ENDER_DRAGON_GROWL"

Scoreboard:
    linesAmount: 8
    kills: 6
    deaths: 5
    kdr: 4
    ckillstreak: 3
    bkillstreak: 2
  
# Wether or not to immediatly consume consumables (potions, food, etc)
immediateConsuming: true

# Wether or not to clear a players inventory upon login
clearInventory: true

WorldGuard:
    disableWandPvP: true
    
    # How much blocks from the players location relative to the border 
    # should be shown.
    # If visibleBorderLeeway is set to 2, the players will see 25 blocks in 
    # the border (5*5).
    # Default: 2 
    visibleBorderLeeway: 2
    
    # The block with which the border will be shown.
    # Default: RED_STAINED_GLASS
    visibleBorderBlock: RED_STAINED_GLASS

# Magic Wand settings
wand:
    enabled: true
    name: '&5Magic Wand'
    material: STICK
    
    # gives enchanted glow
    enchanted: true
    
    # cooldown in seconds for wand use. Set to 0 for no cooldown
    cooldown: 10
    
    secondaryCooldown: 10
    secondaryUse: 5
    
    secondaryDamage: 0.25
    
    # the lore for the item
    lore:
    - 'Left Click: '&3strike your foes with &6lightning from olympus itself&3!'
    - 'Right Click: '&3punish those who oppose you!'

# Dragon stick settings
dragonstick:
    enabled: true
    name: '&6&lStick of the &4&lDragon'
    material: BLAZE_ROD
    
    # gives enchanted glow
    enchanted: true

    # cooldown in seconds for wand use. Set to 0 for no cooldown
    cooldown: 15
    
    secondaryCooldown: 15
    secondaryUse: 5
    
    secondaryDamage: 0.4
    
    # the lore for the item
    lore:
    - 'Left Click: &3make thine enemies explode!'
    - 'Right Click: &3burn thine enemies ALIVE!'
    
# Data storage settings
storage:
    
    # Which storage type to use. Either YML, MYSQL or SQLITE.
    # Default: MYSQL
    type: MYSQL
    
    # Wether or not to keep player stats in memory.
    # Note: this can strain the memory, only use this in case of slow 
    # database connection.
    # Default: false
    keepInMemory: false
    
    host: localhost
    port: 3306
    database: alchemicpvp
    user: pvp
    password: pvp-inator2000