Stats:
  potionEffect: false
  deathMessages: true

Nickname:
  allowFormat: false
  characterlimit: 15
  
Message:
  mentionTag: "@"
  mentionColour: "&b&n"
  receiveSound: "ENTITY_CHICKEN_EGG"
  mentionSound: "ENTITY_ENDER_DRAGON_GROWL"